spring.application.name=backend
# Isso faz o Spring se conectar ao nosso PostgreSQL que está na localmente em cada máquina, na porta 5432, e usar o banco mc656
spring.datasource.url=jdbc:postgresql://localhost:5432/mc656 
# Nome e senha do usuario do PostgreSQ que atribui
spring.datasource.username=mc656_user
spring.datasource.password=mc656_1234

# O Hibernate vai olhar para suas classes @Entity e criar/atualizar as tabelas correspondentes.
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true